### ISSUE TITLE
Does the ssim code support 3d images?

### ISSUE THREAD

**Issue by fairynn** [aizvorski/video-quality#4]

**Comment by fairynn** [comment]
It seems that your code is written for 2d images. I wonder if the code supports 3d images.
Thanks. :)

**Comment by AllenIrving** [comment]
According to the demo file, it seems like the ssim code can be used for 3d images. Just remember to read the image as np.array with np.float32 dtype. Then narrow the pixel value to [0,1] by dividing 255.

**Comment by aizvorski** [comment]
@fairynn The ssim code using the block_view() trick won't work for 3d.  However, the code in ssim_exact() which only relies on gaussian blurs would work - I checked.

In the 3d case, if you're processing 2d images+time (video), you may want to edit the gaussian_filter() calls to have two gaussian blurs, one along the spatial dimensions and one along the time dimension, probably with different sigma values.  If you're processing actual 3d (volumetric) images, assuming the size of a voxel is the same in each dimension, you should be able to use it as is.
